# Generated by Django 5.0.1 on 2024-01-11 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='multistoried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='number_of_stories',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='services_provided',
            field=models.CharField(choices=[('security', 'Security'), ('cctv', 'CCTV Coverage'), ('valet', 'Valet Parking')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
