# Generated by Django 5.0.1 on 2024-02-15 06:39

from django.db import migrations, models

def loadData(apps, schema_editor):
		from django.core.management import call_command
		call_command("loaddata", "ParkingLot")

def deleteData(apps, schema_editor):
		model = apps.get_model("core", "ParkingLot")
		model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
		migrations.RunPython(loadData, deleteData)
    ]
