# Generated by Django 5.0.1 on 2024-01-11 19:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglot_multistoried_parkinglot_number_of_stories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='services_provided',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('security', 'Security'), ('cctv', 'CCTV Coverage'), ('valet', 'Valet Parking')], max_length=15),
        ),
    ]
