# Generated by Django 5.0.1 on 2024-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acaciaslot_mukslot_delete_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('slot_number', models.CharField(max_length=20, unique=True)),
                ('occupied', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AcaciaSlot',
        ),
        migrations.DeleteModel(
            name='MukSlot',
        ),
    ]
