# Generated by Django 5.0.1 on 2024-01-12 19:00

from django.db import migrations, models

def loadData(apps, schema_editor):
		from django.core.management import call_command
		call_command("loaddata", "User")

def deleteData(apps, schema_editor):
		model = apps.get_model("core", "User")
		model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240112_2159'),
    ]

    operations = [
		migrations.RunPython(loadData, deleteData)
    ]
