# Generated by Django 5.0.1 on 2024-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parkinglot_latitude_alter_parkinglot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='services_provided',
            field=models.CharField(max_length=255),
        ),
    ]
