# Generated by Django 5.0.1 on 2024-02-15 06:40

from django.db import migrations, models

def loadData(apps, schema_editor):
		from django.core.management import call_command
		call_command("loaddata", "ParkingSession")

def deleteData(apps, schema_editor):
		model = apps.get_model("core", "ParkingSession")
		model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240215_0940'),
    ]

    operations = [
		migrations.RunPython(loadData, deleteData)
    ]
