# Generated by Django 5.0.1 on 2024-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_status_slot_occupied_alter_slot_parking_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='timestamp_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
