# Generated by Django 5.0.1 on 2024-01-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parkingsession_timestamp_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slot'),
        ),
    ]
