# Generated by Django 5.0.1 on 2024-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parkingsession_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_number',
            field=models.CharField(max_length=10),
        ),
    ]
